[wokwi]
version = 1
firmware = "main/build/arduino.avr.uno/main.ino.hex"

[[chip]]
name = "keyladder"
binary = "buttons-chip/dist/chip.wasm"

[[chip]]
name = "modulator"
binary = "modulator-chip/dist/chip.wasm"
