[wokwi]
version = 1
elf = 'test/keyladder_test/build/arduino.avr.uno/keyladder_test.ino.elf'
firmware = 'test/keyladder_test/build/arduino.avr.uno/keyladder_test.ino.hex'

[[chip]]
name = 'modulator'
binary = 'dist/chip.wasm'
